# Site settings
title: NX Techincal Library
email: harshadfx@yahoo.com
description: >
  Welcome to my first experiment in creating a library for technical books.
  This library will be maintained by NX Drafting team (8th floor) and will initially be only available for Drafting team members.
baseurl: ""
url: "https://harshadfx.github.io/"

# Collections
#collections:
#  books:
#    output: false

sass:
  style: compressed
